- src/providers/docker-images/lambda/Dockerfile
This fixes busted deployments from M1 Macs. This was an exciting ten minutes to hunt down!
> fix: Support building on Apple Silicon / Arm64 platforms

- API.md
- README.md
- SETUP_GITHUB.md
- src/lambdas/delete-runner/index.ts
- src/lambdas/github.ts
- src/lambdas/status/index.ts
- src/lambdas/token-retriever/index.ts
- src/lambdas/webhook-handler/index.ts
- src/runner.ts
- src/secrets.ts
1. Remove client id, client secret, and installation id configuration
2. Get installation id from webhook event to support multiple installations
3. Make it possible to automate app creation with manifests as described in #6
4. Improve status function to list installations and test their authentication
BREAKING CHANGE: backup GitHub auth secret as it will be reset to its default value
> feat: simplify GitHub app installation

- .projen/deps.json
- .projen/tasks.json
- .projenrc.js
- API.md
- README.md
- SETUP_GITHUB.md
- package.json
- src/lambdas/github.ts
- src/lambdas/helpers.ts
- src/lambdas/setup/index.ts
- src/lambdas/status/index.ts
- src/lambdas/webhook-handler/index.ts
- src/runner.ts
- src/secrets.ts
- yarn.lock
Provide an automated way to create GitHub app with manifests, or to set a personal token. This allows the user to easily install everything without manually editing secrets or copying around strings.
Closes #6
> feat: Setup wizard for GitHub integration

- API.md
- README.md
- src/runner.ts
Removed the concept of default provider label as it was confusing and easily caused runners to be left behind. For example, if the user had a typo in the label on the workflow side, the default provider would spin up and never start the job because the labels don't match.
BREAKING CHANGE: `GitHubRunners` no longer takes `defaultProviderLabel` and all workflows must always specify the label they need instead of just `self-hosted`
> feat: No more default provider label

- src/lambdas/update-lambda/index.ts
- src/providers/lambda.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/default.integ.snapshot/manifest.json
- test/default.integ.snapshot/tree.json
The singleton Lambda only got permission to update the code for the first Lambda runner instead of all of them. This happened because we passed the inline policy to the singleton constructor which was only called once.
> fix: All but first Lambda provider broke on rebuild interval

- API.md
- src/providers/common.ts
- src/providers/image-builders/codebuild.ts
- src/providers/image-builders/container.ts
- src/providers/lambda.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/default.integ.snapshot/manifest.json
- test/default.integ.snapshot/tree.json
This affected Lambda runners and Windows runners.
We create images as part of the stack, but we also update them on a schedule and delete the old ones. That means any stack update that touches just the runner and not the image will fail. It will fail because the Lambda function or CodeBuild project will be updated, but the stack will still try to update it with the old image as it's not aware of the new image. This code forces the stack to always get the latest image digest for Lambda, even if the image wasn't created by the stack. On the Windows side, we just tell it to use the 'latest' tag, so we don't have to worry about this issue. That means it's now just a Lambda runner problem and can be confined in the Lambda runner code. Lambda is the only runner provider that needs a digest …
> fix: Failure to update runner if image hasn't changed

- .projen/deps.json
- .projenrc.js
- package.json
- src/lambdas/update-lambda/index.ts
- src/providers/lambda.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/default.integ.snapshot/manifest.json
- test/default.integ.snapshot/tree.json
- yarn.lock
Use a simpler method to avoid conflicts when updating the function code after the image is updated. Instead of looking for a running stack operation, just try again in a loop every 10 seconds. The current code assumed some special handling in CloudFormation that would update the function later. It wasn't working. I believe it was broken by #103.
> fix: Lambda image not updating while stack is deployed

- API.md
- src/providers/codebuild.ts
- src/providers/docker-images/codebuild/linux-arm64/Dockerfile
- src/providers/docker-images/codebuild/linux-x64/Dockerfile
- src/providers/docker-images/fargate/linux-arm64/Dockerfile
- src/providers/docker-images/fargate/linux-x64/Dockerfile
- src/providers/docker-images/lambda/linux-arm64/Dockerfile
- src/providers/docker-images/lambda/linux-arm64/runner.sh
- src/providers/docker-images/lambda/linux-x64/Dockerfile
- src/providers/docker-images/lambda/linux-x64/runner.sh
- src/providers/fargate.ts
- src/providers/image-builders/container.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/default.integ.snapshot/manifest.json
- test/default.integ.snapshot/tree.json
Some GitHub Enterprise instances forbid runners from using --disableupdate. We only truly need it when a user a chooses a specific runner version. When we update the runner image with its version every week, disabling updates shouldn't matter anyway. GitHub Actions seems to only auto-update the runner if we're two versions behind and that would be very rare in the span of a week (default image rebuild interval).
Originally we wanted to disable auto-updates because our runners are ephemeral and updating them for every single job would be wasteful. Since they only auto-update if we're two versions behind, I feel like we can drop this flag.
Fixes #112
Replaces #120
> fix: Avoid --disableupdate for better compatibility

- src/lambdas/setup/index.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/default.integ.snapshot/manifest.json
- test/default.integ.snapshot/tree.json
Apparently Firefox doesn't support nonce in `Content-Security-Policy` and we must use `'unsafe-inline'`.
Beef up security with restrictions on `base-uri` and `object-src` while we're here.
Fixes #141
> fix: Setup doesn't load on Firefox

- setup/src/App.svelte
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/default.integ.snapshot/manifest.json
- test/default.integ.snapshot/tree.json
We were always sending the string `"false"` as `public` in the manifest because the binding was wrong. It's supposed to be a boolean. GitHub was not happy about it and failed to create the app.
> fix: GitHub Enterprise setup fails while complaining about `"public": "false"`

- src/providers/docker-images/lambda/linux-arm64/runner.sh
- src/providers/docker-images/lambda/linux-x64/runner.sh
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/default.integ.snapshot/manifest.json
- test/default.integ.snapshot/tree.json
This happens because Lambdas don't set the HOME environment variable or even create a home directory. It seems like npm guesses the home directory and fails because it's not writable. This fix will create a writable home directory and set HOME environment variable to it.
Fixes #153
> fix: Lambda runners can't use npm install

- src/providers/docker-images/codebuild/linux-arm64/Dockerfile
- src/providers/docker-images/codebuild/linux-x64/Dockerfile
- src/providers/docker-images/fargate/linux-arm64/Dockerfile
- src/providers/docker-images/fargate/linux-x64/Dockerfile
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/default.integ.snapshot/manifest.json
- test/default.integ.snapshot/tree.json
Certain packages like tzdata and keyboard-configuration prompt the user for information. This causes apt-get to hang while waiting for input that will never come. We need to tell apt-get user input is not allowed as it's not available while building a Docker image.
Fixes #154
> fix: Image builder getting stuck in apt-get

- API.md
- src/index.ts
> fix: Add missing export for Ec2Runner

- API.md
- src/providers/ec2.ts
- src/providers/image-builders/ami.ts
- src/providers/image-builders/common.ts
- Use same VPC for default AMI builder of EC2 provider. This makes it easier to use when there is no default VPC in the account.
- Accept vpc and subnetSelection instead of a subnet like the rest of the library (subnet prop is now deprecated).
- Make subnetSelection truly optional by using the default VPC subnet when it's not specified. Previously it reverted to the default VPC unless both vpc and subnetSelection were specified.
Closes #163
> feat: Easier subnet selection for EC2 provider

- src/providers/image-builders/ami.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/default.integ.snapshot/manifest.json
We need to create a new version number for AMI recipe when the parent AMI changes. That can happen every deploy because the parent AMI is dynamically queried for the latest id.
> fix: Resource of type 'AWS::ImageBuilder::ImageRecipe' with identifier 'ImageRecipeArn' already exists.

- API.md
- src/providers/image-builders/ami.ts
- src/providers/image-builders/container.ts
- src/providers/image-builders/linux-components.ts
- src/providers/image-builders/windows-components.ts
> fix: ContainerImageBuilder.addExtraCertificates and AmiBuilder.addExtraCertificates do not work on Linux

- src/lambdas/delete-ami/index.ts
- src/providers/image-builders/ami.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/default.integ.snapshot/manifest.json
- test/default.integ.snapshot/tree.json
We need to manually delete EBS snapshots as they are not automatically deleted when deregistering AMIs.
Fixes #184
> fix: EBS snapshots are not cleaned-up along with AMIs

- API.md
- src/providers/codebuild.ts
- test/providers.test.ts
Give the user the ability to turn off Docker-in-Docker (dind) support, which lets us use non-privileged CodeBuild projects. These projects should provision faster and not require us to wait for Docker to start-up.
Fixes #195
> feat: Optional faster CodeBuild provider without privileged mode

- src/providers/common.ts
- src/providers/ec2.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/default.integ.snapshot/manifest.json
- test/default.integ.snapshot/tree.json
Previously we only used the first subnet due to a limitation of ec2:RunInstances. This fix adds step function states to try all subnets one by one until one works. This should avoid issues where some instance types are not available on certain availability zones. Unlike the old way of not specifying a subnet, this should work for both the default VPC and a custom VPC.
We use Parallel block (with one branch so not really parallel) to enable retrying of the whole thing when all subnets fail.
Fixes #214
> fix: Try running EC2 instances in all selected subnets

- API.md
- src/providers/image-builders/ami.ts
- test/default.integ.snapshot/tree.json
- test/imagebuilder.test.ts
Since Docker Desktop requires a license for big companies, users may want to skip installing it on certain runner images built for Windows.
Fixes #215
> feat: Option to not install Docker Desktop

- src/providers/image-builders/codebuild.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/default.integ.snapshot/manifest.json
- test/default.integ.snapshot/tree.json
Replace with 5.0. This upgrades us from Ubuntu 18.04 to 20.04. The version doesn't matter too much because all we do with this image is run `docker build`.
Fixes #236
> fix: CodeBuild Standard 4.0 is deprecated

- API.md
- README.md
- src/providers/codebuild.ts
- src/providers/ec2.ts
- src/providers/fargate.ts
- src/providers/image-builders/static.ts
- src/providers/lambda.ts
- src/runner.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/default.integ.snapshot/manifest.json
- test/default.integ.ts
- test/labels.test.ts
- test/providers.test.ts
- test/runner.test.ts
This should make it clear they are providers and not actual runners. They provide runners by lunching resources with the right image to start a runner.
Old names remain for now but marked as deprecated.
Fix #168
> chore: Rename xyzRunner to xyzRunnerProvider

- src/providers/docker-images/lambda/linux-arm64/runner.sh
- src/providers/docker-images/lambda/linux-x64/runner.sh
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/default.integ.snapshot/manifest.json
- test/default.integ.snapshot/tree.json
If the Lambda doesn't have a coldstart, the runner will fail because `/tmp/home` already exists.
> fix: Ignore failure on creation of /tmp/home

- src/providers/docker-images/lambda/linux-arm64/runner.sh
- src/providers/docker-images/lambda/linux-x64/runner.sh
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/default.integ.snapshot/manifest.json
- test/default.integ.snapshot/tree.json
The `/tmp` directory can have some files left behind from previous runs when a Lambda instance is reused. We want a clean home directory and clean `/tmp` directory so one run can break the next one.
See #242
> fix: Clean-up Lambda /tmp directory for a fresh runner

- src/lambdas/aws-image-builder-versioner.lambda.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/default.integ.snapshot/manifest.json
- test/default.integ.snapshot/tree.json
AWS Image Builder APIs don't go over all resources by themselves when filters are applied. We still need to manually iterate everything with `nextToken`. This caused our code to not find all deployed versions. The code then assumed 1.0.1 which was already in use.
> fix: AWS Image Builder identifier 'ComponentArn' already exists

- .github/workflows/self-hosted.yml
GitHub Actions don't check if any single commands are failing while using the default shell (PowerShell). Switch to bash so we don't ignore errors.
https://github.com/actions/runner-images/issues/6668
Fixes #253
> fix: Don't ignore Windows integration test results

- src/providers/ecs.ts
- src/providers/image-builders/aws-image-builder/builder.ts
- src/providers/image-builders/aws-image-builder/deprecated/ami.ts
- src/providers/image-builders/aws-image-builder/deprecated/common.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/default.integ.snapshot/manifest.json
- test/default.integ.snapshot/tree.json
[AWS recommends using IMDSv2](https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/); there's even a [migration guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-metadata-transition-to-version-2.html). Sadly, AIUI due to backwards compatibility concerns, it isn't the default _yet_.
`$WORK` requires the use of IMDSv2 for all our EC2 instances … and our use of cdk-github-runners is triggering all sorts of security monitoring alarms.
Any chance we can require the use of IMDSv2 in them? It _should_ be harmless **and** the [normal EC2 provider already requires it](https://github.com/CloudSnorkel/cdk-github-runners/blob/0c46eee82028ab318ec26d0fb1c0a515fd500667/src/providers/ec2.ts#L404).
n.b. …
> fix: Require IMDSv2 in the AWS Image Builder and ECS instances

- API.md
- src/providers/image-builders/aws-image-builder/builder.ts
- src/providers/image-builders/aws-image-builder/deprecated/ami.ts
- src/providers/image-builders/aws-image-builder/deprecated/linux-components.ts
- src/providers/image-builders/aws-image-builder/deprecated/windows-components.ts
> fix: Remove double `set -ex` in deprecated builders

- src/providers/image-builders/aws-image-builder/builder.ts
- src/providers/image-builders/aws-image-builder/deprecated/common.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/default.integ.snapshot/manifest.json
- test/default.integ.snapshot/tree.json
IMSDv2 (#276) broke building runner Docker images for Windows. Container builds require a minimum of two hops.
> fix: Windows runner Docker image builds

- API.md
- src/image-builders/aws-image-builder/deprecated/ami.ts
- src/image-builders/aws-image-builder/deprecated/windows-components.ts
- src/image-builders/components.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
It never worked. The pre-installed `dockerd` with Windows containers was the one that was functioning. We no longer have that pre-installed as we're not using the ECS-optimized base AMI.
This change installs `dockerd` just like ECS-optimized AMIs do. It also sets up `docker-compose`.
Related #252
Related #218
> fix: Don't install Docker Desktop on Windows

- src/image-builders/components.ts
The code was trying to load an asset relative to the source file, but assets are always located in the `assets` folder. This only worked in development because the assets are still next to the source code while developing. All assets must always be loaded from the `assets` folder.
Fixes #305
> fix: Lambda image unable to find runner.js

- src/providers/ecs.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
Get AMI from SSM during instance deployment instead of stack deployment. This requires a switch to launch templates as they support the new `resolve:ssm:...` format for AMI.
https://docs.aws.amazon.com/autoscaling/ec2/userguide/using-systems-manager-parameters.html
> feat: Always use latest AMI for ECS instances

- src/image-builders/aws-image-builder/builder.ts
- src/image-builders/aws-image-builder/deprecated/container.ts
- src/image-builders/codebuild-deprecated.ts
- src/image-builders/codebuild.ts
- src/image-builders/static.ts
- src/providers/common.ts
- src/providers/lambda.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
```
github-runners-test |  0/21 | 5:15:22 PM | UPDATE_FAILED        | AWS::IAM::Policy                               | ECS Windows/Launch Template Role/DefaultPolicy (ECSWindowsLaunchTemplateRoleDefaultPolicy48457459) Unable to retrieve ImageUri attribute for AWS::ImageBuilder::Image, with error message Resource of type 'AWS::ImageBuilder::Image' with identifier '{"/properties/Arn":"arn:aws:imagebuilder:us-east-1:859319237877:image/github-runners-test-windowsimagebuilder-containerrecipe-c577a80b/1.0.4/1"}' was not found.
github-runners-test |  0/21 | 5:15:23 PM | UPDATE_FAILED        | AWS::ECS::TaskDefinition                       | Fargate-Windows/task (FargateWindowstask9F9B942D) Unable to retrieve ImageUri attribute for AWS::ImageBuilder::Image, with error message Resource of type …
```
> fix: Unable to retrieve ImageUri attribute for AWS::ImageBuilder::Image

- API.md
- src/access.ts
It affects the entire VPC. It also prevents us from having two of these endpoints in the same VPC. Finally, not all externally created endpoints will have private DNS enabled.
Fixes #325
> fix: Don't use private DNS for VPC endpoints

- API.md
- src/runner.ts
- test/runner.test.ts
Let the user easily provide access to GitHub Enterprise Server without creating a security group. Make `GitHubRunners` implement `ec2.IConnectable`.
```
const runners = new GitHubRunners(stack, 'runners', {
vpc: vpc,
});
runners.connections.allowTo(ghesSg, ec2.Port.tcp(443));
```
Fixes #332 by creating one security group for all management Lambda functions. This is what users would do anyway when they have to modify access. We only let users pass one set of security groups for all functions, so now we match that behavior for the default case.
> feat: Easier management Lambda security group control

- src/webhook-handler.lambda.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
This helps debugging issues by making it simpler to associate jobs with runner infrastructure.
The URL is only for the job that triggered the runner, but the job the runner executes might be different. That's because GitHub randomly assigns jobs to runners based on labels alone.
> feat: Include job url in step function input

- src/providers/ecs.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
The defaults for ECS only clean-up a container between 10 minutes and one hour after it's done. With the potential for our container to be very big, storage can run out real quick.
This fix forces ECS to clean-up stopped containers within seconds after they're done.
> fix: Faster storage clean-up on ECS

- API.md
- src/idle-runner-repear.lambda.ts
- src/providers/common.ts
- src/runner.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
Try harder to not let a job stay pending. Retry whenever a runner fails for any reason.
The only gotcha here is idle runners. We don't want to let runners wait forever for a job in case it was cancelled. That's a waste of money. Our way of stopping idle runners by deleting them causes the runner process to fail. This bubbles up to the step function with a generic error. We won't be able to filter out that error in the step function to avoid endless retries on idle runners.
```
2023-05-20T22:23:33.612Z	72ef520c-0b31-4343-bba8-11057e3f860d	ERROR	An error occurred: Access denied. System:ServiceIdentity;DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD needs View permissions to perform the action.
2023-05-20T22:23:33.619Z	72ef520c-0b31-4343-bba8-11057e3f860d	INFO	Runner listener exit with retryable error, …
```
> feat: More aggressive retries

- src/image-builders/aws-image-builder/builder.ts
- src/image-builders/aws-image-builder/deprecated/ami.ts
- src/image-builders/aws-image-builder/deprecated/common.ts
- src/image-builders/aws-image-builder/deprecated/container.ts
- src/providers/codebuild.ts
- src/providers/ec2.ts
- src/providers/ecs.ts
- src/providers/fargate.ts
- src/utils.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
Let users execute a command inside the runner containers for debugging. This uses SSM Session Manager. For EC2 it's a button in the console. For ECS/Fargate it's the `aws ecs execute-command` CLI.
We can't enable it for CodeBuild because that requires using batch builds. The required code was left commented out.
This also reduces the permissions given to runners for SSM Session Manager. Instead of using the `AmazonSSMManagedInstanceCore` managed policy, we supply only the bare minimum of permissions. We no longer give everything `ssm:GetParameters` on `*` that comes with `AmazonSSMManagedInstanceCore`.
Fixes #101
> feat: Enable command execution in ECS, Fargate and EC2

- src/image-builders/aws-image-builder/ami.ts
- src/image-builders/aws-image-builder/builder.ts
- src/image-builders/aws-image-builder/deprecated/ami.ts
- src/image-builders/aws-image-builder/deprecated/common.ts
- src/image-builders/aws-image-builder/deprecated/container.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
Undo #361 972d085
`AmazonSSMManagedInstanceCore` is sadly required here. It's less of a big deal as the image builders themselves don't run any user code from GitHub Actions. It will be nice to limit this policy in the future, but I couldn't find any decent documentation on the required permissions.
> chore: Fix AWS Image Builder

- src/webhook-handler.lambda.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
We pass `installationId` from the input into some parts of the step function. We can't use `undefined` or it won't show up in the input and the step function will fail.
Fixes #404
> fix: Using personal access token fails on installationId

- .projen/deps.json
- .projenrc.js
- package.json
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- yarn.lock
BREAKING CHANGE: CDK 2.77.0 and above is required
> chore: Get rid of Node 14.x in tests

- src/providers/ec2.ts
> chore: aws-cdk-lib.aws_stepfunctions.TaskStateBaseProps#heartbeat is deprecated

- .github/workflows/self-hosted.yml
- src/status.lambda.ts
- src/webhook-handler.lambda.ts
- src/webhook.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
When GitHub environments are used, we get the `queued` webhook twice. Once when the job is first queued and another when the job is approved for deployment into the specific environment. This causes two runners to be started for the same job. This wastes resources.
To fix this, we check `dpeloyment.statuses_url` in the payload. If it exists, it contains a URL with details about the deployment status. When the deployment is still pending, the first item in the array will have `status: 'waiting'`. Once the deployment is approved and runners can actually run it, the first item in the array will have `status: 'queued'`. So if the status of the deployment is `waiting`, we don't start a runner. When the second webhook comes in, the status will be `queued` and we can start a runner.
Fixes #380
> fix: Don't start two runners with GitHub environments/deployments

- API.md
- README.md
- src/runner.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/default.integ.ts
Use `GitHubRunners.createLogsInsightsQueries()` to create some useful Logs Insights queries that help diagnose GitHub integration issues.
Fix #393
> feat: Optional Logs Insights queries to help diagnose issues

- SETUP_GITHUB.md
- setup/src/App.svelte
- src/webhook-handler.lambda.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
We added a workaround for double runners when using GitHub deployments/environments with #416. For private repositories using deployments/environments, this requires a new permission for the GitHub app or personal access token. The new required permission is [read-only for deployments](https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-deployments).
This PR updates the documentation and the automated setup process to reflect this new requirement. It also makes this new required permission optional for better backwards compatibility with existing installations.
If you need to add this permission to an existing installation, follow these steps:
1. Generate a new `status.json` using something like `aws --region …
> fix: Missing permission for new double runner protection with GitHub environments

- API.md
- src/runner.ts
- src/webhook-handler.lambda.ts
- src/webhook.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
> feat: Option to not require self-hosted label

- API.md
- src/image-builders/api.ts
- src/image-builders/common.ts
- src/providers/ecs.ts
- src/providers/fargate.ts
JSII returned `Construct` instead of `RunnerImageBuilder` because `RunnerImageBuilder` inherits from `RunnerImageBuilderBase` which is marked internal. To resolve this, we instead return the same object as a new public interface called `IConfigurableImageBuilder`.
We still want vanilla `IRunnerImageBuilder` as someone might want their own version of a builder that may not need components or network configuration. Just like `StaticRunnerImage.fromEcrRepository()``.
This probably failed on Java, .NET and Go too.
Fixes #468
> fix: JSII error while configuring image builders on Python

- src/image-builders/aws-image-builder/builder.ts
- src/image-builders/codebuild.ts
- test/imagebuilder.test.ts
When a builder is created but not used, calling `failedImageBuildsTopic()` raises an exception.
```
No child with id: 'CodeBuild'
```
or
```
No child with id: 'Infrastructure'
```
For example, this would trigger the exceptions:
```
const app = new cdk.App();
const stack = new cdk.Stack(app, 'test');
const vpc = new ec2.Vpc(stack, 'vpc');
LambdaRunnerProvider.imageBuilder(stack, 'codebuild builder');
Ec2RunnerProvider.imageBuilder(stack, 'ec2 image builder', { vpc });
new GitHubRunners(stack, 'runners', {
providers: [new LambdaRunnerProvider(stack, 'p1' /* not using builder on purpose */)],
}).failedImageBuildsTopic();
app.synth();
```
Fixes #490
> fix: No child with id: 'CodeBuild' or 'Infrastructure'

- src/image-builders/aws-image-builder/builder.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
When multiple AMI builders were used in the same stack, the custom resource used to clean up AMIs on delete only had access to delete AMIs for one of the builders.
The error looked like:
```
Received response status [FAILED] from custom resource. Message returned: You are not authorized to perform this operation. User: arn:aws:sts::0123456789:assumed-role/github-runners-test-deleteamidcc036c8876b451ea2c15-0123456789/github-runners-test-deleteamidcc036c8876b451ea2c15-0123456789 is not authorized to perform: ec2:DeregisterImage on resource: arn:aws:ec2:us-east-1::image/ami-079195c0509e4a902 because no identity-based policy allows the ec2:DeregisterImage action.
```
> fix: AMI cleaner not authorized to perform: ec2:DeregisterImage with multiple builders

- src/image-builders/aws-image-builder/deprecated/container.ts
- src/image-builders/build-image.lambda.ts
- src/image-builders/codebuild.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
Support setting longer timeouts for image runner builds. Previously we used custom resources that are limited to 1 hour. Now we will use a wait handle with support for up to 8 hours (the maximum CodeBuild supports). We now also confirm the requested timeout is supported and fail early if it doesn't.
This doesn't affect:
* AMI builds
* Windows Docker image builds
* Explicit AWS Image Builder builds (`builderType: RunnerImageBuilderType.AWS_IMAGE_BUILDER`)
Don't forget to set the builder timeout with:
```
const fargateX64Builder = FargateRunnerProvider.imageBuilder(stack, 'Fargate builder', {
codeBuildOptions: {
timeout: cdk.Duration.hours(8), // 8 hours is the max supported by CodeBuild
},
});
```
Fixes #540
> fix: Support longer runner image build timeouts

- src/image-builders/codebuild.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
This issue was not part of any release. It was caused by #543.
The image was rebuilt on deploys where nothing has changed due to inconsistent hashing. CDK tokens pointing to assets made their way into the hash components.
> fix: Runner image re-built on deploy even without changes

- API.md
- src/image-builders/aws-image-builder/builder.ts
- src/image-builders/codebuild.ts
- src/image-builders/common.ts
- src/providers/lambda.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
If you add a lot of components to your runner image that can take a long time to build, you may want your CDK deployment to not wait for the image to finish. This can speed up the trial-and-error cycle of updating your image. It can make sure a random timeout in the image build process won't roll everything back.
Note that this does have some downsides.
1. Updating components doesn't trigger a new build. You may have to wait up to a week (rebuild interval) for a new image, unless you manually trigger it.
2. Fresh deployments will not be ready to use until the image is done. CDK deployment being done won't mean your setup is ready as the runner image may not be built yet.
3. With the right build timing, some resources may be left behind on stack destruction. This includes log groups and …
> feat: Option to speed up deploys by not waiting for runner images to build

- src/image-builders/aws-image-builder/container.ts
- src/image-builders/aws-image-builder/deprecated/container.ts
When trying to build a Docker runner image using AWS Image Builder, an error like this pops up:
```
github-runners-test |  21 | 10:30:50 PM | CREATE_FAILED        | AWS::ImageBuilder::ContainerRecipe             | Fargate builder no wait 5/Container Recipe/Recipe (Fargatebuildernowait5ContainerRecipeE02237FD) Resource handler returned message: "The value supplied for parameter 'parentImage' is not valid. You must specify a platform override when using ECR Public Repositories as your parent image. (Service: Imagebuilder, Status Code: 400, Request ID: 23846b6b-dfc4-4f05-8444-998238125330)" (RequestToken: 43be45ef-513a-4616-330e-c27d0d39fada, HandlerErrorCode: InvalidRequest)
```
Sample code:
```
FargateRunnerProvider.imageBuilder(stack, 'Fargate builder no wait 5', {
builderType: …
```
> fix: Unable to build Linux Docker runner images with AWS Image Builder

- .projen/deps.json
- .projenrc.js
- package.json
- src/idle-runner-repear.lambda.ts
- src/image-builders/aws-image-builder/builder.ts
- src/image-builders/aws-image-builder/common.ts
- src/image-builders/aws-image-builder/delete-ami.lambda.ts
- src/image-builders/aws-image-builder/filter-failed-builds.lambda.ts
- src/image-builders/aws-image-builder/versioner.lambda.ts
- src/image-builders/build-image.lambda.ts
- src/image-builders/codebuild.ts
- src/providers/ami-root-device.lambda.ts
- src/providers/common.ts
- src/providers/lambda.ts
- src/providers/update-lambda.lambda.ts
- src/runner.ts
- src/utils.ts
- src/webhook-handler.lambda.ts
- src/webhook.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- yarn.lock
Create and share log groups for all of our Lambda functions instead of using the built-in log groups. Switched to structured JSON logging for Lambda functions. This allows for easier debugging with all the relevant logs going to one group. All built-in Log Insights queries created with `createLogsInsightsQueries()` have been updated accordingly and more queries were added.
There are now three shared log groups:
1. **Runner Image Build Helpers Log** for functions related to building runner images like image registration and clean-up
2. **Orchestrator Log** for functions that handle GitHub webhook and triggering runners
3. **Setup Log** for functions that handle initial setup
Resolves #539
BREAKING CHANGE: CDK 2.123.0 and above is required
BREAKING CHANGE: log groups have moved and all …
> feat: Logging improvements for internal Lambda functions

- src/image-builders/codebuild.ts
- src/providers/codebuild.ts
It hangs the build because it can't contact CloudWatch or CloudFormation
> fix: Don't allow public subnets on CodeBuild

- API.md
- src/image-builders/aws-image-builder/builder.ts
- src/image-builders/aws-image-builder/common.ts
- src/image-builders/aws-image-builder/versioner.lambda.ts
- src/image-builders/aws-image-builder/workflow.ts
- src/image-builders/codebuild.ts
- src/image-builders/common.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
Add a new `dockerSetupCommands` property to runner image builders that lets you run arbitrary commands before `docker build` is called. Use this property to specify login commands such as `docker login` or `aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 1234567890.dkr.ecr.us-east-1.amazonaws.com`.
For example:
```typescript
const myBuilder = FargateRunnerProvider.imageBuilder(this, 'image builder', {
baseDockerImage: 'some-private-image:latest',
dockerSetupCommands: [
'DOCKER_USER=$(aws ssm get-parameter --name /github-runners/docker-user --query Parameter.Value --output text)',
'DOCKER_PASS=$(aws ssm get-parameter --name /github-runners/docker-pass --query Parameter.Value --output text)',
'docker login -u $DOCKER_USER -p $DOCKER_PASS'
],
}); …
```
> feat: Enable using private base Docker images

- src/providers/ec2.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
The single quote prevented variable substitution. The configuration file contained literally `$logGroupName`. I'm not sure how this ever worked. Maybe the PowerShell version just got upgraded in the base AMI?
Fixes #564
> fix: Windows EC2 runner logs stopped working

- API.md
- src/providers/common.ts
- src/providers/ec2.ts
- src/providers/ecs.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/default.integ.ts
Set volume type, IOPS and throughput with `storageOptions` for EC2 and ECS providers.
```
new Ec2RunnerProvider(stack, 'EC2 Linux', {
labels: ['ec2', 'linux', 'x64'],
storageSize: cdk.Size.gibibytes(500),
storageOptions: {
volumeType: EbsDeviceVolumeType.IO1,
iops: 30000,
},
});
```
Resolves #621
> feat: Storage options for EC2 and ECS

- src/image-builders/components.ts
Installing Docker on Amazon Linux 2 based images failed with:
```
4.636 No package docker available.
4.879 Error: Nothing to do
------
Dockerfile:19
--------------------
17 |
18 |     COPY component5-Docker.sh /tmp
19 | >>> RUN /tmp/component5-Docker.sh
20 |
21 |     COPY component6-GithubRunner.sh /tmp
--------------------
ERROR: failed to solve: process "/bin/sh -c /tmp/component5-Docker.sh" did not complete successfully: exit code: 1
```
Fixes #646
> fix: "No package docker available" on AL2

- src/image-builders/aws-image-builder/builder.ts
- src/providers/ec2.ts
- test/providers.test.ts
Throw an exception during build time if the EC2 runner storage size is smaller than the AMI size set in the image builder. Before this change, code like this:
```typescript
new GitHubRunners(stack, 'runners', {
providers: [
new Ec2RunnerProvider(stack, 'EC2 Linux', {
imageBuilder: Ec2RunnerProvider.imageBuilder(stack, 'EC2 Linux Builder', {
awsImageBuilderOptions: {
storageSize: cdk.Size.gibibytes(100),
},
}),
storageSize: cdk.Size.gibibytes(30),
}),
],
});
```
could result in errors in the step function that are harder to debug:
```
Ec2.Ec2Exception: Volume of size 30GB is smaller than snapshot 'snap-0123456789abc', expect size>= 100GB
```
> fix: Fail early for storage size mismatch in EC2

- src/providers/fargate.ts
- test/providers.test.ts
- Corrected the logical grouping of the nullish coalescing operator and ternary operator for the ephemeralStorageGiB property.
- Ensured that the ephemeralStorageGiB property is correctly set when provided in the props.
- This fix ensures that the correct storage value is reflected in the synthesized CloudFormation template.
- Prior to this fix the storage value would always be set to 25
> fix: Fargate provider storage size setting doesn't work

- src/webhook-handler.lambda.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
- test/webhook.test.ts
Some code accidentally made its way into to the last release that caused invalid step function execution name. They are supposed to be based on the webhook delivery id, but they were just random. This could cause accidental webhook redeliveries to start too many runners.
See #739
> fix: Duplicate webhook prevention regression in 0.14.9

- src/idle-runner-repear.lambda.ts
- src/runner.ts
- test/default.integ.snapshot/github-runners-test.assets.json
- test/default.integ.snapshot/github-runners-test.template.json
When the GitHub app is installed on multiple repos and/or organization, they can each get a different installation id. Idle reaper handler kept one Octokit instance with the first installation id it found in its input. Octokit cannot be shared. We need a different one for each installation id. That means that if multiple jobs came in around the same time, idle reaper would fail to get data on some of them.
This issue could lead to runners being left behind when the app is installed on multiple repos.
> fix: Idle runner reaper can fail with multiple installations
