README.md
src/providers/codebuild.ts
src/providers/docker-images/codebuild/Dockerfile
src/providers/docker-images/fargate/Dockerfile
src/providers/docker-images/lambda/Dockerfile

Allow jobs running with CodeBuild runners to build and run Docker images.
Closes #1

feat(codebuild): Docker-in-Docker support

---

.projenrc.js
package.json

https://github.com/cdklabs/construct-hub/issues/900

chore: organization is a bool, fix constructs.dev

---

README.md

docs: Fix mix-up between PyPI and NPM links

---

.projen/tasks.json
.projenrc.js

This removes the WSL requirement
See https://github.com/projen/projen/pull/2004

chore: Use shx instead of bash

---

src/lambdas/aws-image-builder-versioner/index.ts
src/lambdas/build-image/index.ts
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json
test/default.integ.snapshot/manifest.json
test/default.integ.snapshot/tree.json

See https://github.com/aws/aws-cdk/pull/20899/ for details

fix: Don't log sensitive response URL

---

API.md
src/index.ts
src/lambdas/status/index.ts
src/providers/codebuild.ts
src/providers/common.ts
src/providers/fargate.ts
src/providers/image-builders/codebuild.ts
src/providers/image-builders/container.ts
src/providers/lambda.ts
src/runner.ts
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json
test/default.integ.snapshot/manifest.json
test/default.integ.snapshot/tree.json

feat: Report runner image and its build logs in status.json

---

test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json
test/default.integ.snapshot/manifest.json
test/default.integ.snapshot/tree.json
test/default.integ.ts

Avoid NAT gateways by just putting Fargate containers on a public subnet
👋 @QuinnyPig

chore: Cheaper integration tests

---

src/providers/docker-images/lambda/linux-arm64/runner.js
src/providers/docker-images/lambda/linux-arm64/runner.sh
src/providers/docker-images/lambda/linux-x64/runner.js
src/providers/docker-images/lambda/linux-x64/runner.sh
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json
test/default.integ.snapshot/manifest.json
test/default.integ.snapshot/tree.json

Trying to use AWS API with Lambda runners resulted in:
Unable to locate credentials. You can configure credentials by running "aws configure".
We were passing only our own environment variables to the runner and blocked AWS_* with the credentials.
See #113

fix: Lambda runners not getting AWS role

---

src/providers/docker-images/codebuild/linux-arm64/Dockerfile
src/providers/docker-images/codebuild/linux-x64/Dockerfile
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json
test/default.integ.snapshot/manifest.json
test/default.integ.snapshot/tree.json

The runner user didn't have permission to write to /home/runner/.docker
Fixes #117
Broke in #106

fix: Unable to update Docker settings in CodeBuild

---

API.md
src/providers/fargate.ts

feat: Subnet selection for Fargate provider

---

API.md
src/providers/image-builders/container.ts
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json
test/default.integ.snapshot/manifest.json
test/default.integ.snapshot/tree.json

Also add ability to override parent image for ContainerImageBuilder
Fixes #130

fix: Unable to build Windows images on anything but us-east-1

---

API.md
src/providers/codebuild.ts
src/providers/ec2.ts
src/providers/fargate.ts
src/providers/lambda.ts
src/runner.ts
src/utils.ts

chore: Make all props structures optional

---

API.md
src/index.ts
src/providers/image-builders/index.ts
src/providers/index.ts

fix: Export AmiBuilder

---

src/providers/ec2.ts
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json
test/default.integ.snapshot/manifest.json
test/default.integ.snapshot/tree.json

fix: The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances

---

README.md

actions-runner-controller has been officially adopted by GitHub and so has moved home https://github.com/actions-runner-controller/actions-runner-controller/issues/3

docs: update arc to point at new home

---

src/lambdas/status/index.ts
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json
test/default.integ.snapshot/manifest.json
test/default.integ.snapshot/tree.json

LaunchTemplateVersions can be undefined

chore: Resolve TypeScript error

---

.github/workflows/self-hosted.yml
src/providers/image-builders/linux-components.ts
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json
test/default.integ.snapshot/manifest.json
test/default.integ.snapshot/tree.json

fix: Allow sudo in EC2 runners

---

src/providers/ec2.ts
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json
test/default.integ.snapshot/manifest.json
test/default.integ.snapshot/tree.json

Windows, bless its heart, can take a while to boot-up. Wait longer before giving up on it and also retry or try a new subnet if it timed out.

fix: Less strict EC2 timeouts

---

src/providers/ec2.ts
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json
test/default.integ.snapshot/manifest.json
test/default.integ.snapshot/tree.json

This helps integration test snapshots become more stable. It's not ideal, but without it there is a token in the node name, and its number changes with every little code change.

chore: Move subnet id to comment

---

API.md
src/providers/image-builders/codebuild.ts

feat: Option to override CodeBuild image builder image

---

src/providers/fargate.ts
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json
test/default.integ.snapshot/manifest.json
test/default.integ.snapshot/tree.json

fix: Fargate provider used --disableupdate when version was latest

---

src/image-builders/aws-image-builder/builder.ts
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json

fix: Clean-up old Docker images built by AWS Image Builder

---

API.md
src/access.ts
test/access.test.ts

feat: Option to use existing VPC endpoint for Lambda access

---

API.md
src/providers/ecs.ts
test/providers.test.ts

fix: Custom capacity provider for ECS was broken

---

src/idle-runner-repear.lambda.ts
src/runner.ts
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json

This issue was never a part of a release

fix: Only run one instance of idle reaper per runner

---

src/webhook-handler.lambda.ts
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json

Add logging of the owner, repo, job id, job url, and labels. This will make it easier to trace executions all the way from GitHub to the runner.
```
2023-06-18T20:57:30.898000+00:00 2023/06/18/[$LATEST]22ea57d30bae409ea7d190a2e025627b 2023-06-18T20:57:30.898Z  915f2a6b-cc2e-469e-99f2-01a7498b05c1 INFO    {"owner":"CloudSnorkel","repo":"cdk-github-runners","jobId":14357392993,"jobUrl":"https://github.com/CloudSnorkel/cdk-github-runners/actions/runs/5305690503/jobs/9602813506","installationId":30891679,"labels":{"self-hosted":true,"linux":true,"lambda":true,"x64":true}}
```

feat: Enhance webhook logs

---

src/status.lambda.ts
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json

Thanks @chrisneal
Replaces #376

fix: Allow access to status page when setup is disabled 

---

src/delete-failed-runner.lambda.ts
src/idle-runner-repear.lambda.ts
src/image-builders/aws-image-builder/delete-ami.lambda.ts
src/image-builders/aws-image-builder/filter-failed-builds.lambda.ts
src/image-builders/aws-image-builder/reaper.lambda.ts
src/image-builders/aws-image-builder/versioner.lambda.ts
src/setup.lambda.ts
src/status.lambda.ts
src/token-retriever.lambda.ts
src/webhook-handler.lambda.ts
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json
test/versioner.test.ts
test/webhook.test.ts

This will help us ensure dependency upgrades don't break anything.
We should add tests for GitHub API too, but I'm not too sure how yet.

chore: Unit test for Lambda code

---

src/providers/ecs.ts
src/webhook-handler.lambda.ts
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json

The ECS optimized image didn't contain AWS CLI.
Fixes #408

fix: Pre-pull runner image on ECS

---

src/providers/lambda.ts
test/imagebuilder.test.ts

fix: Don't allow wrong OS for Lambda runner provider

---

src/runner.ts
test/runner.test.ts

fix: Don't deploy without any providers

---

API.md
src/providers/ecs.ts
test/providers.test.ts

feat: Memory reservation option for ECS runners

---

src/runner.ts

fix: Remove deprecated StateMachineProps#definition usage

---

.projen/tasks.json
.projenrc.js
setup/.eslintrc.json
setup/src/main.ts

chore: Automatically run eslint on setup folder

---

src/image-builders/aws-image-builder/builder.ts
src/image-builders/codebuild.ts
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json

fix: Replace deprecated property for cleaning up ECR repositories

---

src/webhook-handler.lambda.ts
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json

fix: Long repository names caused naming conflicts

---

.github/workflows/self-hosted.yml
API.md
src/image-builders/components.ts
test/components.test.ts
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json
test/default.integ.ts

```
const myBuilder = FargateRunnerProvider.imageBuilder(this, 'image builder');
myBuilder.addComponent(
RunnerImageComponent.environmentVariables({
HELLO: 'world',
FOO: 'bar',
})
);
const myProvider = new FargateRunnerProvider(this, 'fargate runner', {
labels: ['fargate-with-env-vars'],
imageBuilder: myBuilder,
});
new GitHubRunners(this, 'runners', {
providers: [myProvider],
});
```
Resolves #509

feat: Support for setting runner environment variables

---

src/providers/fargate.ts
test/default.integ.snapshot/github-runners-test.assets.json
test/default.integ.snapshot/github-runners-test.template.json

This issue was never present in a release. It was caused by #630.

fix: Windows Fargate/ECS stopped working due to runner groups
